// Generated by CoffeeScript 2.0.0-beta7
angular.module('Gleemail').controller('ConfigForm', function ($scope) {
  return $scope.onSubmit = function () {
    if ($scope.config)
      configResource.save({ id: $scope.displayedTemplate.name }, $scope.config);
    return $scope.showConfig = false;
  };
});
