// Generated by CoffeeScript 2.0.0-beta7
angular.module('Gleemail').controller('Preview', function ($rootScope, $scope) {
  var displayTemplate, socket;
  $scope.iframeSrc = '';
  displayTemplate = function (template) {
    var cacheBuster;
    cacheBuster = new Date().getTime();
    return $scope.iframeSrc = '/templates/' + template.name + '.html?cache-buster=' + cacheBuster + '&dataIndex=' + $scope.dataIndex;
  };
  $scope.$watch('displayedTemplate', function (template) {
    if (template)
      return displayTemplate(template);
  });
  $scope.$watch('dataIndex', function (index) {
    if ($scope.displayedTemplate)
      return displayTemplate($scope.displayedTemplate);
  });
  socket = io('http://localhost');
  return socket.on('connect', function () {
    return socket.on('template-updated', function (template) {
      console.log('template-update', template, $scope.displayedTemplate);
      if (template.name === (null != $scope.displayedTemplate ? $scope.displayedTemplate.name : void 0))
        return $scope.$apply(function () {
          return displayTemplate($scope.displayedTemplate);
        });
    });
  });
});
