/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var appConfig, EloquaClient, renderEmailTemplate, request, templateConfig;
  request = require('request');
  appConfig = require('./config');
  templateConfig = require('./template-config');
  renderEmailTemplate = require('./render-email-template');
  module.exports = EloquaClient = function () {
    function EloquaClient(param$) {
      this.templateName = param$;
    }
    EloquaClient.prototype.save = function (cb) {
      return this._loadTemplateConfig(function (this$) {
        return function (err, config) {
          var options;
          options = {
            useAbsoluteUrls: true,
            renderer: 'eloqua'
          };
          return renderEmailTemplate(this$.templateName, 'text', options, function (this$1) {
            return function (err, plainText) {
              if (err)
                return cb(err);
              return renderEmailTemplate(this$1.templateName, 'html', options, function (this$2) {
                return function (err, html) {
                  var payload;
                  if (err)
                    return cb(err);
                  payload = {
                    bouncebackEmail: null,
                    emailFooterId: null,
                    emailGroupId: null,
                    emailHeaderId: null,
                    encodingId: null,
                    folderId: null,
                    htmlContent: {
                      type: 'RawHtmlContent',
                      html: html
                    },
                    isPlainTextEditable: false,
                    name: this$2.templateName,
                    plainText: plainText,
                    replyToEmail: null != config.replyTo ? config.replyTo.email : void 0,
                    replyToName: null != config.replyTo ? config.replyTo.name : void 0,
                    senderEmail: null != config.sender ? config.sender.email : void 0,
                    senderName: null != config.sender ? config.sender.name : void 0,
                    sendPlainTextOnly: false,
                    subject: config.subject || ''
                  };
                  if (config.eloquaId) {
                    payload.id = config.eloquaId;
                    payload.updatedAt = new Date().toISOString();
                    payload.updatedBy = appConfig.eloqua.username;
                  } else {
                    payload.createdAt = new Date().toISOString();
                    payload.createdBy = appConfig.eloqua.username;
                  }
                  return this$2.deliver(payload, cb);
                };
              }(this$1));
            };
          }(this$));
        };
      }(this));
    };
    EloquaClient.prototype.deliver = function (payload, cb) {
      return this._withEloquaHost(function (this$) {
        return function (err, host) {
          var opts;
          if (err)
            return cb(err);
          opts = {
            method: 'POST',
            url: '' + host + '/API/REST/1.0/assets/email',
            headers: { Authorization: this$._auth() },
            json: payload
          };
          return request(opts, function (this$1) {
            return function (err, response, body) {
              if (err)
                return cb(err);
              if (!this$1.config.eloquaId) {
                this$1.config.eloquaId = body.id;
                this$1.config.save();
              }
              return cb(null, body);
            };
          }(this$));
        };
      }(this));
    };
    EloquaClient.prototype._withEloquaHost = function (cb) {
      var opts;
      opts = {
        method: 'GET',
        url: 'https://login.eloqua.com/id',
        headers: { Authorization: this._auth() }
      };
      return request(opts, function (err, response, body) {
        var e, parsed;
        if (err)
          return cb(err);
        try {
          parsed = JSON.parse(body);
          return cb(null, body.urls.base);
        } catch (e$) {
          e = e$;
          return cb(e);
        }
      });
    };
    EloquaClient.prototype._loadTemplateConfig = function (cb) {
      if (this.config)
        return cb(null, this.config);
      return templateConfig(this.templateName, function (this$) {
        return function (err, config) {
          if (err)
            console.error("Error loading template config for '" + this$.templateName + "'", err);
          this$.config = config;
          return cb(null, this$.config || {});
        };
      }(this));
    };
    EloquaClient.prototype._auth = function () {
      var encoded, pair;
      pair = '' + appConfig.eloqua.company + '\\' + appConfig.eloqua.username + ':' + appConfig.eloqua.password;
      encoded = new Buffer(pair).toString('base64');
      return 'Basic ' + encoded;
    };
    return EloquaClient;
  }();
}.call(this);
