// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var app, bodyParser, Broadcaster, broadcaster, config, express, FileWatcher, fs, hooks, http, port, routes, server, watcher;
  http = require('http');
  fs = require('fs');
  express = require('express');
  routes = require('./routes');
  FileWatcher = require('./file-watcher');
  Broadcaster = require('./broadcaster');
  bodyParser = require('body-parser');
  hooks = require('./hooks');
  port = process.env.PORT || 4433;
  app = express();
  server = http.createServer(app);
  broadcaster = new Broadcaster(server);
  config = require('./config');
  app.use(express['static']('' + __dirname + '/../../public'));
  app.use(bodyParser());
  routes(app);
  server.listen(port);
  console.log('Running Gleemail at localhost:' + port);
  hooks._load();
  watcher = FileWatcher.instance();
  watcher.init();
  watcher.on('template-updated', function (template) {
    return broadcaster.broadcast('template-updated', template);
  });
}.call(this);
