/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var _, cheerio, Litmus, mail, request;
  request = require('request');
  mail = require('nodemailer').mail;
  cheerio = require('cheerio');
  _ = require('underscore');
  module.exports = Litmus = function () {
    function Litmus(options) {
      this.html = options.html;
      this.title = options.title;
      this.baseUrl = options.url;
      this.clients = options.clients;
      this.auth = {
        user: options.username,
        pass: options.password
      };
    }
    Litmus.prototype.run = function (cb) {
      return this.litmusId(function (this$) {
        return function (err, id) {
          if (err)
            return cb(err);
          if (id) {
            return this$.updateTest(id, cb);
          } else {
            return this$.createTest(cb);
          }
        };
      }(this));
    };
    Litmus.prototype.litmusId = function (cb) {
      var opts;
      opts = {
        auth: this.auth,
        url: '' + this.baseUrl + '/tests.xml'
      };
      return request.get(opts, function (err, res, body) {
        var $, $name, e, id, title;
        if (err)
          return cb(err);
        try {
          id = null;
          $ = cheerio.load(body, { xmlMode: true });
          title = this.title;
          $name = $('name').filter(function () {
            var $nameTag;
            $nameTag = $(this);
            return $nameTag.text() === title;
          });
          if ($name.length)
            id = $matchedName.parent().children('id').text();
          return cb(null, id);
        } catch (e$) {
          e = e$;
          return cb(e);
        }
      });
    };
    Litmus.prototype.parseStatus = function (body) {
      var $, avgTimes, delayed, seconds, statuses, unavailable;
      $ = cheerio.load(body, { xmlMode: true });
      statuses = $('status');
      delayed = [];
      unavailable = [];
      seconds = 0;
      avgTimes = $('average_time_to_process');
      avgTimes.each(function (i, el) {
        return seconds += parseInt($(this).text(), 10);
      });
      seconds = Math.round(seconds / avgTimes.length);
      statuses.each(function (i, el) {
        var $this, appName, statusCode;
        $this = $(this);
        statusCode = parseInt($this.text(), 10);
        appName = $this.parent().children('application_long_name').text();
        switch (statusCode) {
        case 1:
          return delayed.push(appName);
        case 2:
          return unavailable.push(appName);
        }
      });
      return {
        time: seconds,
        delayed: delayed,
        unavailable: unavailable
      };
    };
    Litmus.prototype.createTest = function (cb) {
      var opts;
      opts = {
        auth: this.auth,
        headers: {
          'Content-type': 'application/xml',
          Accept: 'application/xml'
        },
        body: this.xml(),
        url: '' + this.baseUrl + '/emails.xml'
      };
      return request.post(opts, function (this$) {
        return function (err, res, body) {
          var e, status;
          if (err)
            return cb(err);
          try {
            status = res.headers.status;
            if (!/^2/.test(status))
              return cb(status);
            status = this$.parseStatus(body);
            return cb(null, status);
          } catch (e$) {
            e = e$;
            return cb(e);
          }
        };
      }(this));
    };
    Litmus.prototype.updateTest = function (id, cb) {
      var opts;
      opts = {
        auth: this.auth,
        headers: {
          'Content-type': 'application/xml',
          Accept: 'application/xml'
        },
        body: this.xml(),
        url: '' + this.baseUrl + '/tests/' + id + '/versions.xml'
      };
      return request.post(opts, function (this$) {
        return function (err, res, body) {
          if (err)
            return cb(err);
          return this$.mailNewVersion(body, function (this$1) {
            return function (err) {
              var e, status;
              if (err)
                return cb(err);
              try {
                status = this$1.parseStatus(body);
                return cb(null, status);
              } catch (e$) {
                e = e$;
                return cb(e);
              }
            };
          }(this$));
        };
      }(this));
    };
    Litmus.prototype.mailNewVersion = function (body, cb) {
      var $, e, guid;
      try {
        $ = cheerio.load(body);
        guid = $('url_or_guid').text();
        mail({
          from: 'no-reply@test.com',
          to: guid,
          subject: this.title,
          text: '',
          html: this.html
        });
        return cb();
      } catch (e$) {
        e = e$;
        return cb(e);
      }
    };
    Litmus.prototype.xml = function () {
      var client, xml;
      xml = '<?xml version="1.0"?>\n<test_set>\n  <save_defaults>false</save_defaults>\n  <use_defaults>false</use_defaults>\n  <email_source>\n    <body>\n      <![CDATA[' + this.html + ']]>\n    </body>\n    <subject>' + this.title + '</subject>\n  </email_source>\n  <applications type="array">';
      for (var i$ = 0, length$ = this.clients.length; i$ < length$; ++i$) {
        client = this.clients[i$];
        xml += '<application>\n  <code>' + client + '</code>\n</application>';
      }
      xml += '  </applications>\n</test_set>';
      return xml;
    };
    return Litmus;
  }();
}.call(this);
