/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var config, createTemplate, deliverEmail, EloquaClient, FileWatcher, fs, Litmus, LITMUS_CLIENTS, pathLib, renderEmailTemplate, renderers, renderOptions, templateConfig, templates;
  fs = require('fs');
  pathLib = require('path');
  config = require('./config');
  Litmus = require('./litmus-client');
  FileWatcher = require('./file-watcher');
  renderEmailTemplate = require('./render-email-template');
  EloquaClient = require('./eloqua-client');
  deliverEmail = require('./deliver-email');
  createTemplate = require('./create-template');
  templateConfig = require('./template-config');
  renderers = require('./transformers/template').renderers;
  templates = require('./templates');
  LITMUS_CLIENTS = [
    'android22',
    'android4',
    'aolonline',
    'androidgmailapp',
    'appmail6',
    'iphone5s',
    'ipadmini',
    'ipad',
    'gmailnew',
    'ffgmailnew',
    'chromegmailnew',
    'iphone4',
    'iphone5',
    'ol2007',
    'ol2010',
    'ol2011',
    'ol2013',
    'outlookcom',
    'ffoutlookcom',
    'chromeoutlookcom',
    'plaintext',
    'yahoo',
    'ffyahoo',
    'chromeyahoo',
    'windowsphone8'
  ];
  module.exports = function (app) {
    app.get('/config.json', function (req, res) {
      return res.json(config);
    });
    app.get('/templates.json', function (req, res) {
      return templates.all(function (err, templates) {
        if (err)
          return res.status(500).send(err);
        return res.send(templates);
      });
    });
    app.get('/templates/:templateName.html', function (req, res) {
      return renderEmailTemplate(req.params.templateName, 'html', renderOptions(req), function (err, contents) {
        if (err)
          return res.status(500).send(err);
        return res.send(contents);
      });
    });
    app.get('/templates/:templateName.txt', function (req, res) {
      return renderEmailTemplate(req.params.templateName, 'text', renderOptions(req), function (err, contents) {
        if (err)
          return res.status(500).send(err);
        return res.send(contents);
      });
    });
    app.get('/templates/:templateName/images/:path', function (req, res) {
      return fs.readFile('' + config.root + '/templates/' + req.params.templateName + '/images/' + req.params.path, function (err, img) {
        if (err)
          return res.status(500).send(err);
        return res.send(img);
      });
    });
    app.post('/templates/:templateName/litmus', function (req, res) {
      return renderEmailTemplate(req.params.templateName, 'html', renderOptions(req, { useAbsoluteUrls: true }), function (err, contents) {
        var litmusClient;
        if (err)
          return res.status(500).send(err);
        litmusClient = new Litmus({
          username: config.litmus.username,
          password: config.litmus.password,
          url: config.litmus.url,
          clients: LITMUS_CLIENTS,
          html: contents,
          title: 'TEST: ' + req.params.templateName
        });
        return litmusClient.run(function (err, status) {
          if (err)
            return res.status(500).send(err);
          return res.status(200).send(status);
        });
      });
    });
    app.post('/templates/:templateName/email', function (req, res) {
      var recipient, templateName;
      templateName = req.params.templateName;
      recipient = req.params.email;
      if (!recipient)
        return res.status(400).send({ error: 'No email received' });
      return deliverEmail(templateName, [recipient], renderOptions(req, { useAbsoluteUrls: true }), function (err) {
        if (err)
          return res.status(500).send(err);
        return res.send('ok');
      });
    });
    app.post('/templates', function (req, res) {
      var templateName;
      templateName = req.params.templateName;
      if (!templateName)
        return res.status(404).send('not found');
      return createTemplate(templateName, function (err, path) {
        if (err)
          return res.status(500).send(err);
        FileWatcher.instance().watchTemplate(templateName);
        return res.send('ok');
      });
    });
    app.post('/templates/:templateName/eloqua', function (req, res) {
      var client;
      client = new EloquaClient(req.params.templateName);
      return client.save(function (err, payload) {
        if (err)
          return res.status(500).send(err);
        return res.send(payload);
      });
    });
    app.get('/templates/:templateName/config', function (req, res) {
      return templateConfig(req.params.templateName, function (err, tconfig) {
        if (err)
          return res.status(500).send(err);
        return res.send(tconfig);
      });
    });
    app.post('/templates/:templateName/config', function (req, res) {
      return templateConfig(req.params.templateName, req.body, function (err, tconfig) {
        if (err)
          return res.status(500).send(err);
        return tconfig.save(function (err) {
          if (err)
            return res.status(500).send(err);
          return res.send(req.body);
        });
      });
    });
    app.get('/renderers', function (req, res) {
      var keys;
      keys = Object.keys(renderers);
      return res.send(keys.map(function (key) {
        return {
          key: key,
          label: renderers[key].label
        };
      }));
    });
    return app.get('*', function (req, res) {
      return res.sendFile(pathLib.resolve('' + __dirname + '/../../public/index.html'));
    });
  };
  renderOptions = function (req, overrides) {
    var k, options, v;
    if (null == overrides)
      overrides = {};
    options = {
      useAbsoluteUrls: req.params.useAbsoluteUrls === 'true',
      renderer: req.params.renderer,
      dataIndex: req.params.dataIndex ? parseInt(req.params.dataIndex, 10) : void 0
    };
    for (var i$ = 0, length$ = overrides.length; i$ < length$; ++i$) {
      k = overrides[i$];
      v = i$;
      options[k] = v;
    }
    return options;
  };
}.call(this);
