/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var config, Config, fs, isArray;
  fs = require('fs');
  config = require('./config');
  isArray = require('underscore').isArray;
  Config = function () {
    function Config(param$, data) {
      var k, v;
      this.templateName = param$;
      if (null == data)
        data = {};
      for (k in data) {
        if (!isOwn$(data, k))
          continue;
        v = data[k];
        this[k] = v;
      }
    }
    Config.prototype.load = function (cb) {
      if (null == cb)
        cb = function () {
        };
      return fs.readFile(this.path(), function (this$) {
        return function (err, buffer) {
          var data, e, k, v;
          if (err && err.code !== 'ENOENT')
            return cb(err);
          try {
            data = buffer ? JSON.parse(buffer.toString()) : {};
            for (k in data) {
              if (!isOwn$(data, k))
                continue;
              v = data[k];
              this$[k] = v;
            }
            return this$.loadData(function (this$1) {
              return function (err, data) {
                this$1.dataLength = data.length;
                return cb(null, this$1);
              };
            }(this$));
          } catch (e$) {
            e = e$;
            return cb(e);
          }
        };
      }(this));
    };
    Config.prototype.loadData = function (cb) {
      if (null == cb)
        cb = function () {
        };
      return fs.readFile(this.dataPath(), function (err, buffer) {
        var data, e;
        if (err && err.code !== 'ENOENT')
          return cb(err);
        try {
          data = buffer ? JSON.parse(buffer.toString()) : {};
          if (!isArray(data))
            data = [data];
          return cb(null, data);
        } catch (e$) {
          e = e$;
          return cb(e);
        }
      });
    };
    Config.prototype.save = function (cb) {
      var e, k, out, text, v;
      if (null == cb)
        cb = function () {
        };
      out = {};
      for (k in this) {
        if (!isOwn$(this, k))
          continue;
        v = this[k];
        if (!(k !== 'templateName'))
          continue;
        out[k] = v;
      }
      try {
        text = JSON.stringify(out);
      } catch (e$) {
        e = e$;
        return cb(e);
      }
      return fs.writeFile(this.path(), text, function (err) {
        return cb(err);
      });
    };
    Config.prototype.path = function () {
      return '' + config.root + '/templates/' + this.templateName + '/.config.json';
    };
    Config.prototype.dataPath = function () {
      return '' + config.root + '/templates/' + this.templateName + '/data.json';
    };
    return Config;
  }();
  module.exports = function (templateName, data, cb) {
    var tconfig;
    if (!cb) {
      cb = data;
      data = null;
    }
    tconfig = new Config(templateName, data);
    if (data) {
      return cb(null, tconfig);
    } else {
      return tconfig.load(cb);
    }
  };
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
}.call(this);
