// Generated by CoffeeScript 2.0.0-beta7
angular.module('Gleemail').config(function ($routeProvider, $locationProvider) {
  $routeProvider.when('/', { templateUrl: '/templates/preview.html' });
  $routeProvider.when('/templates/:id', { templateUrl: '/templates/preview.html' });
  return $locationProvider.html5Mode(true);
});
